// Lab extends Examination
// has a reference to a factory
// has a "current question" that was generated by the factory

import { Factory } from "../Factory";

class Lab extends Examination {
  constructor(title, author, currentQuestion) {
    super(title, author);
    this.currentQuestion = Factory.create();
  }
}

export { Lab };
