export { default as About } from './About.svelte'
export { default as Home } from './Home.svelte'
export { default as NotFound } from './NotFound.svelte'
export * from './COMP1805'
export * from './COMP2804'
