name: Dynamic

on:
  push:
    paths:
      - "dynamic/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - uses: jpetrucciani/black-check@master
      with:
        path: './dynamic'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
    - name: Run PyTest
      run: |
        pytest
