name: Dynamic

on: [push, pull_request]

jobs:
  test-dynamic:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dynamic/requirements.txt
    - name: Run Black linting
      run: |
        black ./dynamic
    - name: Run PyTest
      run: |
        pytest dynamic/
